# Generated by Django 4.1 on 2022-08-18 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crud_models',
            name='product_created_date',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
